package com.practise.galaxyguide.validator;

import com.practise.galaxyguide.validator.RomanNumeralValidator;
import com.practise.galaxyguide.validator.StringValidator;

import junit.framework.TestCase;

public class RomanNumeralValidatorTest extends TestCase {

    public void test_type() throws Exception {
        assertNotNull(RomanNumeralValidator.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanNumeralValidator();
        assertNotNull(target);
    }

    // Null and Empty has already been written.

    public void test_process_good() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanNumeralValidator("IV");
        boolean actual = target.process();
        boolean expected = true;
        assertEquals(expected, actual);
    }

    public void test_process_rep_4() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanNumeralValidator("XXXX");
        boolean actual = target.process();
        boolean expected = false;
        assertEquals(expected, actual);
    }

    public void test_process_rep_2() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanNumeralValidator("DD");
        boolean actual = target.process();
        boolean expected = false;
        assertEquals(expected, actual);
    }

}
