package com.practise.galaxyguide.validator;

import com.practise.galaxyguide.validator.RomanForeignLiteralValidator;
import com.practise.galaxyguide.validator.StringValidator;

import junit.framework.TestCase;

public class RomanForeignLiteralValidatorTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(RomanForeignLiteralValidator.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        RomanForeignLiteralValidator target = new RomanForeignLiteralValidator();
        assertNotNull(target);
    }

    public void test_process_A_bad_null() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanForeignLiteralValidator(null);
        boolean actual = target.validate();
        boolean expected = false;
        assertEquals(expected, actual);
    }

    public void test_process_A_bad_good() throws Exception {
        // TODO auto-generated by JUnit Helper.
        StringValidator target = new RomanForeignLiteralValidator("glob is I");
        boolean actual = target.process();
        boolean expected = true;
        assertEquals(expected, actual);
    }
}
