package com.practise.galaxyguide.interpreter;

import com.practise.galaxyguide.interpreter.Expression;

import junit.framework.TestCase;

public class ExpressionTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(Expression.class);
    }

}
