package com.practise.galaxyguide.interpreter;

import java.util.ArrayList;

import com.practise.galaxyguide.domains.BaseDomain;
import com.practise.galaxyguide.domains.Credits;
import com.practise.galaxyguide.domains.ForeignLiteral;
import com.practise.galaxyguide.domains.RomanAndForeignLiteral;
import com.practise.galaxyguide.domains.RomanNumeralLiteral;
import com.practise.galaxyguide.interpreter.InterpreterContext;
import com.practise.galaxyguide.interpreter.InterpreterFactory;

import junit.framework.TestCase;

public class InterpreterFactoryTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(InterpreterFactory.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        InterpreterContext context_ = null;
        InterpreterFactory target = new InterpreterFactory(context_);
        assertNotNull(target);
    }

    public void test_interpret_A$String() throws Exception {
        BaseDomain actual, expected;

        // TODO auto-generated by JUnit Helper.
        InterpreterContext context_ = new InterpreterContext();
        InterpreterFactory target = new InterpreterFactory(context_);
        String inputLine = "glob is I";
        ArrayList<ForeignLiteral> fwords;

        actual = target.interpret(inputLine);
        expected = new RomanAndForeignLiteral(RomanNumeralLiteral.I, new ForeignLiteral("glob"));
        assertEquals(expected.toString(), actual.toString());

        inputLine = "glob glob silver is 34 credit";
        actual = target.interpret(inputLine);

        fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("silver"));
        expected = new Credits(fwords, 34);
        assertEquals(expected.toString(), actual.toString());

        inputLine = "how much is pish tegj glob glob ?";
        actual = target.interpret(inputLine);

        fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("pish"));
        fwords.add(new ForeignLiteral("tegj"));
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("glob"));
        expected = new Credits(fwords, -1);
        assertEquals(expected.toString(), actual.toString());

        inputLine = "how many credit is glob prok silver ?";
        actual = target.interpret(inputLine);

        fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("prok"));
        fwords.add(new ForeignLiteral("silver"));
        expected = new Credits(fwords, -1);
        assertEquals(expected.toString(), actual.toString());
    }

}
