package com.practise.galaxyguide.interpreter;

import java.util.ArrayList;

import com.practise.galaxyguide.domains.BaseDomain;
import com.practise.galaxyguide.domains.Credits;
import com.practise.galaxyguide.domains.ForeignLiteral;
import com.practise.galaxyguide.domains.RomanAndForeignLiteral;
import com.practise.galaxyguide.domains.RomanNumeralLiteral;
import com.practise.galaxyguide.interpreter.InterpreterContext;

import junit.framework.TestCase;

public class InterpreterContextTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(InterpreterContext.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        InterpreterContext target = new InterpreterContext();
        assertNotNull(target);
    }

    public void test_getRomanLiteral_A$String_bad_null() throws Exception {
        InterpreterContext target = new InterpreterContext();
        String lineInput = null;
        assertNull(target.getRomanLiteral(lineInput));
    }

    public void test_getRomanLiteral_A$String_good() throws Exception {
        InterpreterContext target = new InterpreterContext();
        String lineInput = "glob is I";
        BaseDomain actual = target.getRomanLiteral(lineInput);
        BaseDomain expected = new RomanAndForeignLiteral(RomanNumeralLiteral.I, new ForeignLiteral("glob"));
        assertEquals(expected.toString(), actual.toString());
    }

    public void test_getCredits_A$String() throws Exception {
        // TODO auto-generated by JUnit Helper.
        InterpreterContext target = new InterpreterContext();
        String lineInput = null;
        BaseDomain actual = target.getCredits(lineInput);
        BaseDomain expected = null;
        assertEquals(expected, actual);
    }

    public void testGetCredits() throws Exception {
        InterpreterContext target = new InterpreterContext();
        String lineInput = "glob glob silver is 34 Credits";
        BaseDomain actual = target.getCredits(lineInput);

        ArrayList<ForeignLiteral> fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("silver"));
        BaseDomain expected = new Credits(fwords, 34);
        // assertEquals(expected, actual);
        assertEquals(expected.toString(), actual.toString());
    }

    public void testGetMuchQuestion() throws Exception {
        InterpreterContext target = new InterpreterContext();
        String lineInput = "how much is pish tegj glob glob ?";
        BaseDomain actual = target.getMuchQuestion(lineInput);

        ArrayList<ForeignLiteral> fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("pish"));
        fwords.add(new ForeignLiteral("tegj"));
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("glob"));

        BaseDomain expected = new Credits(fwords, -1);
        assertEquals(expected.toString(), actual.toString());
    }

    public void testGetManyQuestion() throws Exception {
        InterpreterContext target = new InterpreterContext();
        String lineInput = "how many credits is glob prok silver ?";
        BaseDomain actual = target.getManyQuestion(lineInput);

        ArrayList<ForeignLiteral> fwords = new ArrayList<ForeignLiteral>();
        fwords.add(new ForeignLiteral("glob"));
        fwords.add(new ForeignLiteral("prok"));
        fwords.add(new ForeignLiteral("silver"));

        BaseDomain expected = new Credits(fwords, -1);
        assertEquals(expected.toString(), actual.toString());
    }

}
