package com.practise.galaxyguide.domains;

import com.practise.galaxyguide.domains.BaseDomain;
import com.practise.galaxyguide.domains.RomanAndForeignLiteral;

import junit.framework.TestCase;

public class BaseDomainTest extends TestCase {

    public void test_type() throws Exception {
        assertNotNull(BaseDomain.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        BaseDomain target = new RomanAndForeignLiteral();
        assertNotNull(target);
    }
}
