package com.practise.galaxyguide.domains;

import com.practise.galaxyguide.domains.ForeignLiteral;
import com.practise.galaxyguide.domains.RomanAndForeignLiteral;
import com.practise.galaxyguide.domains.RomanNumeralLiteral;

import junit.framework.TestCase;

public class RomanAndForeignLiteralTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(RomanAndForeignLiteral.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        RomanNumeralLiteral romanNumeralLiteral = null;
        ForeignLiteral foreignLiteral = null;
        RomanAndForeignLiteral target = new RomanAndForeignLiteral(romanNumeralLiteral, foreignLiteral);
        assertNotNull(target);
    }

    public void test_toString_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        RomanNumeralLiteral romanNumeralLiteral = RomanNumeralLiteral.C;
        ForeignLiteral foreignLiteral = new ForeignLiteral("glob");
        RomanAndForeignLiteral target = new RomanAndForeignLiteral(romanNumeralLiteral, foreignLiteral);
        String actual = target.toString();
        System.out.println(target);
        String expected = "RomanAndForeignLiteral [romanNumeralLiteral=C, foreignLiteral=glob]";
        assertEquals(expected, actual);
    }

}
